[package]
name = "user/zombiegame"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

Knit = "sleitnick/knit@^1.5.1"

Promise = "evaera/promise@^4.0.0"

janitor = "howmanysmall/janitor@1.18.3"

Signal = "sleitnick/signal@^2.0.1"





[server-dependencies]

ProfileService = "firebird702/profileservice@1.1.0"